### ISSUE TITLE
Courier 3.1.6 on Umbraco 7.15.0 =  Method not found

### ISSUE THREAD

**Issue by abellisai** [umbraco/Umbraco.Courier.Issues#11]
Courier 3.1.6 is not compatible with umbraco 7.15.0.

When i right click on a node on the umbraco tree (Content or media) i obtain an exception, and on the log file i have this error:

`System.MissingMethodException: Method not found: 'Umbraco.Core.Models.EntityBase.IUmbracoEntity Umbraco.Core.Services.IEntityService.Get(Int32, Boolean)'.
   at Umbraco.Courier.UI.CourierTasks.ItemTaskProviders.ContentTasks.GetItemIdentifier(Object treeNodeId)`

Reproduction
------------

Install Umbraco 7.15.0
Install Courier 3.1.6
On Contect section of umbrtaco right click on a node

### Bug summary

With Umbraco 7.15.0 is changhed the interface IEntitySerivce and is missing this method:
`IUmbracoEntity Get(int id, bool loadBaseType = true);`
This cause Courier 3.1.6 crash:
`Umbraco.Web.Trees.ContentTreeController - Unhandled controller exception occurred
System.MissingMethodException: Method not found: 'Umbraco.Core.Models.EntityBase.IUmbracoEntity Umbraco.Core.Services.IEntityService.Get(Int32, Boolean)'.
   at Umbraco.Courier.UI.CourierTasks.ItemTaskProviders.ContentTasks.GetItemIdentifier(Object treeNodeId)`

**Comment by nul800sebastiaan** [comment]
Thanks for the report and very sorry for breaking this. We'll have v7.15.1 ready soon (early next week) which will revert a change that broke Courier.
