### ISSUE TITLE
"Change Document Type" doesn't work correctly with Courier

### ISSUE THREAD

**Issue by sofietoft** [umbraco/Umbraco.Courier.Issues#12]
Using the "Change Document Type" on a content node to change the Document Type being used, the changes are not reflected when using Courier to deploy these changes to the next environment.

### Bug summary
On the target environment, the node will still be using the original Document Type, and the Template field will be empty.
Both frontend and preview for the content node, will throw a YSOD on the target environment as well.

Reproduction
------------
### Specifics
* Umbraco version used: 7.15.1
* Courier version used: 3.1.6

### Steps to reproduce
1. Create a local setup with up to 2 Umbraco environments (in this example: Source and Target) version 7.15.1
2. Install and configure latest Courier version on both environments
3. Create a few Document Types + Templates and content on Source environment (I created 3 Document Types; `HomePage`, `TextPage` and `AltPage` - two of these should be similar, in order to be able to switch between them on content)
3. Create some content on Source environment (I created 1 using `HomePage`, 3 using `TextPage`)
4. Courier everything from Source to Target environment
5. Back on the Source environment; use the "Change Document Type" feature to change the Document Type for one of the content nodes using `TextPage` - I switched it to `AltPage`. Verify that this is all working on Source.
6. Courier this one content node to Target

### Expected result
I expected that the Document Type and Template will have been changed correctly on the Target environment, and that everything would be working fine as on the Source environment.

### Actual result
On the Target environment, the content node is still using the original Document Type (`TextPage`), and no Template is assigned, and from the dropdown, I can only select the old Template.
This is even though the `AltPage` Document Type and Template have been transfered to the Target environment.

Also, when I try to visit the frontend of the content node I'm presented with a YSOD:
![amending-doc-type](https://user-images.githubusercontent.com/24529086/63437348-a5275680-c42a-11e9-930f-4013e8b0f52d.png)
I did try restarting - no change.

#### Potential workaround:
Changing the Document Type used on the Target environment as well.
== Doesn't work, as the Target environment says that no Document Types are compatible with the current one - even though they are compatible on the Source environment.

**Comment by nul800sebastiaan** [comment]
Unfortunately, I believe we never found a way to make Change Doctype work with Courier and Deploy. We even disabled the option to change the document type on Cloud specifically because we could not see a way to track this in Cloud or Deploy at all.

I can't remember the details, but I think @clausjensen can explain more about this.

**Comment by clausjensen** [comment]
@nul800sebastiaan you are correct .. and I was actually typing up a really long reply here explaining it and why we haven't been able to handle it. Doing that - I however came to think of a few things that we haven't considered before and it might actually be possible to support the feature both on Cloud and in local Courier setups.

I'll need a bit of time to think it through and write up a conclusion. And whether the feature will be prioritized for Courier - I can't really say. It's likely we'll be implementing it for Deploy in Cloud, but it cannot be applied directly to Courier as it is a different codebase.

**Comment by clausjensen** [comment]
See comment here: https://github.com/umbraco/Umbraco-Deploy/issues/381#issuecomment-524734670

**Comment by sofietoft** [comment]
Comment from @clausjensen on [https://github.com/umbraco/Umbraco-Deploy/issues/381](https://github.com/umbraco/Umbraco-Deploy/issues/381):

> The bug here is actually that the option to change the document type, is available. It shouldn't be.
It has never been possible to deploy an updated document that had it's document type changed so being able to do that would be considered a feature request.
> I believe we however decided to keep the option available due to the fact that if you delete the existing document in the target environment first (that being the environment the document is being transferred TO regardless of it being a restore or a deploy) - it is perfectly possible to re-transfer the document from source to target, even though it has had its document type changed.
