### ISSUE TITLE
Nested Content images not couriered umbraco 7.15.4

### ISSUE THREAD

**Issue by mjbarlow** [umbraco/Umbraco.Courier.Issues#15]
Nested content is now a part of core, when I try and courier content with Courier 3.1.8,  that has images, then those images aren't included when couriering. They have to be identified in the media section and couriered separately.

Reproduction
------------
Two clean umbraco v 7.15.4 installs, set up a document type that has a nested content property and that property has an image of the type media picker.

Add a content item, and an image then courier the node, the node content will be couriered without the image, resulting in a trashed icon.

<img width="784" alt="2020-03-28 16_29_31-Content - test3 local" src="https://user-images.githubusercontent.com/1984515/77830112-8c042800-7126-11ea-9e04-8039d5c5864c.png">

### Expected result

Expect the image to be couriered.

### Actual result

Image isn't couriered.

**Comment by nul800sebastiaan** [comment]
Did you add the Courier Contrib dll to your install? It includes a data resolver for NC: https://github.com/umbraco/Umbraco.Courier.Contrib

Releases are on NuGet: https://www.nuget.org/packages/Umbraco.Courier.Contrib

**Comment by mjbarlow** [comment]
Okay, thanks, yes adding that worked.
