### ISSUE TITLE
Courier transfer revision error

### ISSUE THREAD

**Issue by ismailmayat** [umbraco/Umbraco.Courier.Issues#16]
Using umbraco 7.15.4 and courier v3.1.8.

I have 2 instances setup staging and uat. So I can courier content from staging to uat and vice versa no problem. 

On uat I created a revision. On staging I can see the revision on uat, when i try to transfer it over i get the following error in chrome console:

> editRemoteRevision.aspx?revision=LDO&repo=https://madeup-uat-somedomain.com&folder=:34 Uncaught TypeError: Cannot read property 'nodeId' of null at ShowTransferModal (editRemoteRevision.aspx?revision=LDO&repo=https://madeup-uat-somedomain.com&folder=:34) at HTMLButtonElement.onclick (editRemoteRevision.aspx?revision=LDO&repo=https://madeup-uat-somedomain.com&folder=:121) ShowTransferModal @ editRemoteRevision.aspx?revision=LDO&repo=https://madeup-uat-somedomain.com&folder=:34 onclick @ editRemoteRevision.aspx?revision=LDO&repo=https://madeup-uat-somedomain.com&folder=:121 VM674 DependencyHandler.axd:4 JQMIGRATE: Migrate is installed, version 1.4.0

**Comment by nul800sebastiaan** [comment]
Hi @ismailmayat - did you get any further with this? Looks like a frontend error? Any luck when you you disable CDF (set `debug="false"` on the environments, might give a better error?

**Comment by ismailmayat** [comment]
@nul800sebastiaan u mean set debug = true right ;-}

**Comment by ismailmayat** [comment]
Tried that with debug true, the console is the same nothing extra

![error](https://user-images.githubusercontent.com/1446692/86128767-b4ab0d80-bad9-11ea-9bf4-d02875f3862b.PNG)


I also checked log files but nothing about courier in there.

**Comment by ismailmayat** [comment]
@nul800sebastiaan withe original ticket i raised I did send zip of sites where you could see the issue, I can resend if you require it?

**Comment by nul800sebastiaan** [comment]
@ismailmayat Oh.. I don't know, is that a support ticket in Zendesk or what are we talking about?

**Comment by ismailmayat** [comment]
I initially raised this as a support ticket in zendesk. I also sent site files so error could be reproduced. I was then directed to create issue in github instead. The ticket id is support 52664.  If you so wish i can send you a zip that has the issue to be honest its just demo site 7.15.4 with courier installed i have 3 sites, when i try and use revisions with those i get same error.

**Comment by nul800sebastiaan** [comment]
@ismailmayat Alright, well I can install a 7.15 site myself of course. 😄 

It turns out this is a javascript error that's very easy to fix:

- Go to `~/Umbraco/Plugins/courier` and open up `editRemoteRevision.aspx`
    - The line `var nodeId = UmbClientMgr.mainTree().getActionNode().nodeId;` is completely unused and can be removed
- Go to to `~/Umbraco/Plugins/courier/pages` and open up `editRemoteRevision.aspx` 
    - The line `var nodeId = UmbClientMgr.mainTree().getActionNode().nodeId;` is completely unused and can be removed

Save these files and deploy them accross your environments, the Transfer button will start working in all environments.

This will be fixed in the next release of Courier.

**Comment by ismailmayat** [comment]
Awesome this works, many thanks @nul800sebastiaan you just saved me a world of pain ;-}
