### ISSUE TITLE
Importing content etc into an environment from another not working

### ISSUE THREAD

**Issue by chyde-rcsg** [umbraco/Umbraco.Courier.Issues#18]
I am not able to import content (using the Courier "Update" functionality) into a properly configured Umbraco environment from another properly configured Umbraco environment.

The error received is:

`System.ArgumentNullException: Value cannot be null.
Parameter name: destination
at Umbraco.Courier.Core.BaseRevisionHandler..ctor(ExecutionContext executionContext, Repository source, Repository destination, String revision)
at Umbraco.Courier.Core.Packaging.RevisionPackaging..ctor(ExecutionContext executionContext, Repository source, Repository destination, String revision)
at Umbraco.Courier.UI.Dialogs.UpdateItem.PackageSelectedItems()
at Umbraco.Courier.UI.Dialogs.UpdateItem.renderSteps()
at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)`

I have been in contact with Umbraco support (through my paid support agreement)  for the last month about this, and have just been directed to create a ticket here. I have provided them my config file (which they said was fine), and actually asked them to make sure my Courier license file was properly defined as well (which they also did).

At this point I am very much in need of a solution here. I am able to deploy content _to_ one defined Umbraco installation from another, but I cannot import content into a defined Umbraco installation _from_ another.

I thank you for your prompt assistance!

Chris Hyde

**Comment by nul800sebastiaan** [comment]
Hi there @chyde-rcsg, that's an interesting feature that you found, I didn't even know that it existed!

It looks like it hasn't been working for a long time https://our.umbraco.com/forum/umbraco-courier/88040-update-not-working-on-courier-express

While maybe not as instant, I would recommend you try it the other way around. On the environment from which you're trying to pull the latest content, you can create a revision and pick what it needs to contain, or just include everything. Then in your local environment you can go to the courier section, open up Locations and then open the location you're trying to pull from. The remote revisions will be listed here and you can transfer and install them locally. 

Give that a go and let us know how you get on.

**Comment by chyde-rcsg** [comment]
Sebastiaan:

I realize it's been a while, but unfortunately we have been busy in other
areas of development that I am just now able to return to this.

We have tried using the "revision" method you describe, and while the site
"appears" to do what it should, the revision contents never actually seem
to get installed on the local site.

For example, we:

Log into the source site and create the revision with the contents we want.
Log into the target site, and through Courier pull down the revision from
the source site.
Once pulled down, we choose to install the revision in the target site.

All through that above process, everything appears to work with no errors
thrown. Unfortunately, after choosing to install and getting no errors, the
contents of the revision are still not actually in the target site.

Any thoughts?

Thanks,
Chris



Chris Hyde
Development Director
chris.hyde@craftedbyredcedar.com
*Red Cedar Solutions Group*
2367 Science Parkway, Suite #1  •  Okemos, Michigan 48864
<https://maps.google.com/?q=2367+Science+Parkway,+Suite+%231%C2%A0%C2%A0%E2%80%A2%C2%A0%C2%A0Okemos,+Michigan+48864&entry=gmail&source=g>
m: 989.277.6949
www.craftedbyredcedar.com
<https://facebook.com/craftedbyredcedar>

**Comment by nul800sebastiaan** [comment]
Hi there @chyde-rcsg, we're writing you today to let you know that Umbraco Courier has entered the security phase earlier this month, as described in the following blog post: [Announcement: Support, LTS and EOL for Umbraco CMS, Cloud and packages](https://umbraco.com/blog/announcement-support-lts-and-eol-for-umbraco-cms-cloud-and-packages/).

This means that we're no longer working on Umbraco Courier issues and in March 2022 we will also stop fixing security issue and Courier is considered EOL (End Of Life) and we no longer recommend using it.

As such, I will be closing this issue.
