### ISSUE TITLE
Bug in LocalLinkResolver.cs prevents most locallinks from being picked up as dependencies

### ISSUE THREAD

**Issue by bowserm** [umbraco/Umbraco.Courier.Issues#20]
I have both an Umbraco 7.15.6 and an Umbraco 7.13.1 site with Courier 3.1.8 installed. Both of them have a problem where if I pick a content node as a locallink in a rich text editor, that new content node is not picked up as a dependency by courier when I deploy. I've included the `localLinks` section of my config file for both of the sites. The `courier.config`s in general are pretty standard. Just custom remotes and some extra content pickers registered in one of them:

```
    <localLinks>
      <localLinksAreDependencies>true</localLinksAreDependencies>
      <!-- Propertytypes that CAN contain locallinks (like the ones inserted with TinyMCE) -->
      <add key="TinyMCE3">Umbraco.TinyMCEv3</add>
      <add key="TextboxMultiple">Umbraco.TextboxMultiple</add>
      <add key="Textstring">Umbraco.Textbox</add>
      <add key="Simple Editor">Umbraco.MarkdownEditor</add>
    </localLinks>
```

Reproduction
------------

### Steps to reproduce

1. Run an Umbraco 7.13+ site (I've only tested on 7.13.1 and 7.15.5 and 7.15.6)
2. Install Courier 3.1.8
3. Set up some content nodes with an RTE data type that uses the `Umbraco.TinyMCEv3` property editor
4. Set up a destination site and configure a remote in the courier.config file to point from your source site to your destination site
5. On your source site, create several new nodes
6. Within the rich text editor on one of the new nodes, create link to another new content node
7. Attempt to deploy the node with the link in the rich text editor to the destination site.

### Expected result

As you are walking through the courier deploy wizard, when it displays the list of dependencies, you should see two `Documents` and two `Property Data`

### Actual result

As you are walking through the courier deploy wizard, when it displays the list of dependencies, you will only see the `Documents` and `Property Data` for the node you are directly deploying. The node picked through the locallink in the rich text editor is not picked up as a dependency.

------------
### Proposed Solution

It looks like in the `Umbraco.Courier.DataResolvers.Helpers.LocalLinkResolver.cs` file in the `ReplaceIdWithGuid` method attempts to parse the entire contents of the RTE as a GuidUdi. It should only be attempting to parse the portion of the string matched by the regular expression. I'm looking at this through a decompiler, so this should be close what what is seen and close to my proposed solution:

#### Actual Method

```
private string ReplaceIdWithGuid(string val, out List<Guid> ids)
{
    Dictionary<int, Match> dictionary = new Dictionary<int, Match>();
    ids = new List<Guid>();
    foreach (Match match in LocalLinkResolver.LocalLinkPattern.Matches(val))
    {
        if (match.Groups.Count > 0)
        {
            int result;
            if (int.TryParse(match.Groups[1].Value, out result))
            {
                dictionary[result] = match;
            }
            else
            {
                Guid guidUdiVal;
                if (UmbracoCompatibilityHelper.HasUdiSupport && val.TryParseGuidUdi(out guidUdiVal))
                {
                    ids.Add(guidUdiVal);
                }
            }
        }
    }
    if (dictionary.Count > 0)
    {
        Dictionary<int, Guid> uniqueIds = this._databasePersistence.GetUniqueIds(dictionary.Keys.ToArray<int>());
        foreach (KeyValuePair<int, Match> keyValuePair in dictionary)
        {
            Match match = keyValuePair.Value;
            if (uniqueIds.ContainsKey(keyValuePair.Key))
            val = val.Replace(match.Value, string.Format("href=\"/{{localLink:{0}}}", (object) uniqueIds[keyValuePair.Key]));
        }
        ids.AddRange((IEnumerable<Guid>) uniqueIds.Values.ToList<Guid>());
    }
    return val;
}
```

It should be something more like

```
private string ReplaceIdWithGuid(string val, out List<Guid> ids)
{
    Dictionary<int, Match> dictionary = new Dictionary<int, Match>();
    ids = new List<Guid>();
    foreach (Match match in LocalLinkResolver.LocalLinkPattern.Matches(val))
    {
        if (match.Groups.Count > 0)
        {
            int result;
            if (int.TryParse(match.Groups[1].Value, out result))
            {
                dictionary[result] = match;
            }
            else
            {
                Guid guidUdiVal;
                if (UmbracoCompatibilityHelper.HasUdiSupport && match.Groups[1].Value.TryParseGuidUdi(out guidUdiVal))
                {
                    ids.Add(guidUdiVal);
                }
            }
        }
    }
    if (dictionary.Count > 0)
    {
        Dictionary<int, Guid> uniqueIds = this._databasePersistence.GetUniqueIds(dictionary.Keys.ToArray<int>());
        foreach (KeyValuePair<int, Match> keyValuePair in dictionary)
        {
            Match match = keyValuePair.Value;
            if (uniqueIds.ContainsKey(keyValuePair.Key))
            val = val.Replace(match.Value, string.Format("href=\"/{{localLink:{0}}}", (object) uniqueIds[keyValuePair.Key]));
        }
        ids.AddRange((IEnumerable<Guid>) uniqueIds.Values.ToList<Guid>());
    }
    return val;
}
```

**Comment by nul800sebastiaan** [comment]
Hi there @bowserm, we're writing you today to let you know that Umbraco Courier has entered the security phase earlier this month, as described in the following blog post: [Announcement: Support, LTS and EOL for Umbraco CMS, Cloud and packages](https://umbraco.com/blog/announcement-support-lts-and-eol-for-umbraco-cms-cloud-and-packages/).

This means that we're no longer working on Umbraco Courier issues and in March 2022 we will also stop fixing security issue and Courier is considered EOL (End Of Life) and we no longer recommend using it.

As such, I will be closing this issue.
