### ISSUE TITLE
Ignore feature for templates doesn't work

### ISSUE THREAD

**Issue by drbldgtl** [umbraco/Umbraco.Courier.Issues#22]
Adding Umbraco.Courier.ItemProviders.TemplateItemProvider to the ignore list under itemProviders has no effect when transferring content.

This has already been reproduced by Umbraco HQ as part of support ticket #55317, this was their description:
"We had 2 environments set up, added in the Umbraco.Courier.ItemProviders.TemplateItemProvider to the ignore list, had the same template on both environments and made a change to one of them, and like you said it does get added even after it has been told to ignore it."

This is using Umbraco 7.15.6 and Courier 3.1.9.

Regardless of whether the templates differ between environments, it should be possible to transfer content without the template being added as a dependency of the content.

There are no error messages to report since the transfer of content continues to work just with incorrect behaviour.

I have attached one screenshot showing configuration and another showing the template being included.

![Screenshot 2020-10-27 202457](https://user-images.githubusercontent.com/6883719/98235839-4fb96580-1f5a-11eb-8740-9484b4ed5eca.png)
![Screenshot 2020-10-27 202032](https://user-images.githubusercontent.com/6883719/98235841-50ea9280-1f5a-11eb-9d20-14a7831488b4.png)

**Comment by nul800sebastiaan** [comment]
I can't seem to find any code relating to this feature. This problem was also reported on the old issue tracker https://issues.umbraco.org/issue/COU-234

Not sure if there's a different way to do this, will have to ask around.

**Comment by nul800sebastiaan** [comment]
Hi there @drbldgtl, we're writing you today to let you know that Umbraco Courier has entered the security phase earlier this month, as described in the following blog post: [Announcement: Support, LTS and EOL for Umbraco CMS, Cloud and packages](https://umbraco.com/blog/announcement-support-lts-and-eol-for-umbraco-cms-cloud-and-packages/).

This means that we're no longer working on Umbraco Courier issues and in March 2022 we will also stop fixing security issue and Courier is considered EOL (End Of Life) and we no longer recommend using it.

As such, I will be closing this issue.
