### ISSUE TITLE
Umbraco Courier 3.1.9 Issue with context Id

### ISSUE THREAD

**Issue by ghost** [umbraco/Umbraco.Courier.Issues#23]
We have Umbraco version 7.7.1 application hosted on Azure environment , we use Courier 3.1.9 package for migrating the data from UAT to production environment . Suddendly we are facing issue with courier where it gives error

"500 : Internal Server Error"

In Courier log we could below mentioned error

"System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> A call to SetContextId must occur before getting/setting a context"

**Comment by nul800sebastiaan** [comment]
Hi @hvjathar - not sure what's going on. Seems to indicate a session authentication error maybe.

I found some references to this error: 
Are you sending to a load-balanced / multi-server environment? https://our.umbraco.com/forum/umbraco-courier/83727-courier-failing-with-contextid-issues

I also found some things referring to SQL CE: Courier doesn't work on that, make sure to use SQL Server.
Additionally, make sure that the credentials on both ends for the user are definitely the same.

**Comment by nul800sebastiaan** [comment]
Hi there @hvjathar, we're writing you today to let you know that Umbraco Courier has entered the security phase earlier this month, as described in the following blog post: [Announcement: Support, LTS and EOL for Umbraco CMS, Cloud and packages](https://umbraco.com/blog/announcement-support-lts-and-eol-for-umbraco-cms-cloud-and-packages/).

This means that we're no longer working on Umbraco Courier issues and in March 2022 we will also stop fixing security issue and Courier is considered EOL (End Of Life) and we no longer recommend using it.

As such, I will be closing this issue.
