### ISSUE TITLE
Datatypes are compared by Id instead of their GUIDs

### ISSUE THREAD

**Issue by waldvmar** [umbraco/Umbraco.Courier.Issues#6]
Datatypes are matched by ID instead of by GUIDs with Courier. 

Reproduction
------------

### Bug summary

When editing a customized data type attached to a customized Doctype and then migrating the Doctype with Courier to another instance (which already contained that Doctype incl. this customized Datatype), the Following sometimes happens:
The customized data type is not updated on the target instance or a new data type is created and appended to the existing customized Doctype instead of updating the existing customized data type on the target instance.

So we contacted Courier Support and have been told that Datatypes are matched by ID instead of by GUIDs. This should be fixed. For Doctypes, Nodes and Medias the GUID is already used to match changes with Courier.

### Specifics

- the umbraco version is 7.12.3
- the Courier version is 3.1.6.0

### Steps to reproduce

- editing a customized data type attached to a customized Doctype
- migrate the Doctype with Courier to another instance (which already contained that Doctype incl. this customized Datatype)

### Expected result

- customized Doctype and customized Datatype on target instance should be updated and same as on source instance

### Actual result

The customized data type is not updated on the target instance or a new data type is created and appended to the existing customized Doctype instead of updating the existing customized data type on the target instance.

**Comment by nul800sebastiaan** [comment]
For custom datatypes you'll need to add a resolver to fix this, examples of resolvers can be found in this project: https://github.com/umbraco/Umbraco.Courier.Contrib
